[2023-09-01T06:19:12.692+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bash_test.task1 manual__2023-09-01T06:19:11.020221+00:00 [queued]>
[2023-09-01T06:19:12.705+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bash_test.task1 manual__2023-09-01T06:19:11.020221+00:00 [queued]>
[2023-09-01T06:19:12.706+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-09-01T06:19:12.723+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task1> on 2023-09-01 06:19:11.020221+00:00
[2023-09-01T06:19:12.731+0000] {standard_task_runner.py:57} INFO - Started process 7030 to run task
[2023-09-01T06:19:12.737+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bash_test', 'task1', 'manual__2023-09-01T06:19:11.020221+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/test_dags2.py', '--cfg-path', '/tmp/tmpgcy7kc77']
[2023-09-01T06:19:12.742+0000] {standard_task_runner.py:85} INFO - Job 45: Subtask task1
[2023-09-01T06:19:12.815+0000] {task_command.py:415} INFO - Running <TaskInstance: bash_test.task1 manual__2023-09-01T06:19:11.020221+00:00 [running]> on host 8ef33824b8b6
[2023-09-01T06:19:12.928+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bash_test' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2023-09-01T06:19:11.020221+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-01T06:19:11.020221+00:00'
[2023-09-01T06:19:12.931+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-01T06:19:12.934+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dags && python module/crawling.py -s hankook -c politics']
[2023-09-01T06:19:12.976+0000] {subprocess.py:86} INFO - Output:
[2023-09-01T06:19:14.087+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-09-01T06:19:14.089+0000] {subprocess.py:93} INFO -   File "module/crawling.py", line 131, in <module>
[2023-09-01T06:19:14.090+0000] {subprocess.py:93} INFO -     main()
[2023-09-01T06:19:14.092+0000] {subprocess.py:93} INFO -   File "module/crawling.py", line 103, in main
[2023-09-01T06:19:14.095+0000] {subprocess.py:93} INFO -     with open('config/category.yaml', 'r') as f:
[2023-09-01T06:19:14.096+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'config/category.yaml'
[2023-09-01T06:19:14.144+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-09-01T06:19:14.161+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-01T06:19:14.169+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bash_test, task_id=task1, execution_date=20230901T061911, start_date=20230901T061912, end_date=20230901T061914
[2023-09-01T06:19:14.214+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 45 for task task1 (Bash command failed. The command returned a non-zero exit code 1.; 7030)
[2023-09-01T06:19:14.243+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-01T06:19:14.271+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
