[2023-09-03T07:46:33.384+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawling_news.society scheduled__2023-09-01T15:10:00+00:00 [queued]>
[2023-09-03T07:46:33.411+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawling_news.society scheduled__2023-09-01T15:10:00+00:00 [queued]>
[2023-09-03T07:46:33.414+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-09-03T07:46:33.445+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): society> on 2023-09-01 15:10:00+00:00
[2023-09-03T07:46:33.459+0000] {standard_task_runner.py:57} INFO - Started process 26228 to run task
[2023-09-03T07:46:33.468+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crawling_news', 'society', 'scheduled__2023-09-01T15:10:00+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/crawling_dag.py', '--cfg-path', '/tmp/tmp1u2zkawm']
[2023-09-03T07:46:33.471+0000] {standard_task_runner.py:85} INFO - Job 125: Subtask society
[2023-09-03T07:46:33.598+0000] {task_command.py:415} INFO - Running <TaskInstance: crawling_news.society scheduled__2023-09-01T15:10:00+00:00 [running]> on host 8ef33824b8b6
[2023-09-03T07:46:33.735+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crawling_news' AIRFLOW_CTX_TASK_ID='society' AIRFLOW_CTX_EXECUTION_DATE='2023-09-01T15:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-01T15:10:00+00:00'
[2023-09-03T07:46:33.743+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-03T07:46:33.748+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/ && python src/crawling.py -s hankook -c society -d 20230902']
[2023-09-03T07:46:33.770+0000] {subprocess.py:86} INFO - Output:
[2023-09-03T07:46:36.326+0000] {subprocess.py:93} INFO - Society ['HC01', 'HC02', 'HC03', 'HC04', 'HC05', 'HC06', 'HC99'] 20230902
[2023-09-03T07:46:36.332+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-09-03T07:46:36.333+0000] {subprocess.py:93} INFO -   File "src/crawling.py", line 153, in <module>
[2023-09-03T07:46:36.336+0000] {subprocess.py:93} INFO -     main()
[2023-09-03T07:46:36.339+0000] {subprocess.py:93} INFO -   File "src/crawling.py", line 144, in main
[2023-09-03T07:46:36.341+0000] {subprocess.py:93} INFO -     loop.run_until_complete(run(site, main_category, sub_category, date))
[2023-09-03T07:46:36.343+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
[2023-09-03T07:46:36.346+0000] {subprocess.py:93} INFO -     return future.result()
[2023-09-03T07:46:36.348+0000] {subprocess.py:93} INFO -   File "src/crawling.py", line 110, in run
[2023-09-03T07:46:36.350+0000] {subprocess.py:93} INFO -     await asyncio.gather(*futures)
[2023-09-03T07:46:36.352+0000] {subprocess.py:93} INFO -   File "src/crawling.py", line 81, in get_news
[2023-09-03T07:46:36.355+0000] {subprocess.py:93} INFO -     for i in range(1, last_page_number+1):
[2023-09-03T07:46:36.358+0000] {subprocess.py:93} INFO - TypeError: can only concatenate str (not "int") to str
[2023-09-03T07:46:36.532+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-09-03T07:46:36.554+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-03T07:46:36.564+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=crawling_news, task_id=society, execution_date=20230901T151000, start_date=20230903T074633, end_date=20230903T074636
[2023-09-03T07:46:36.596+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 125 for task society (Bash command failed. The command returned a non-zero exit code 1.; 26228)
[2023-09-03T07:46:36.632+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-03T07:46:36.687+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
